[build]
builder = "NIXPACKS"
buildCommand = "npm install --production=false && npm run build && npm prune --production && npx prisma generate"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "5002"

[deploy.env]
DATABASE_URL = "${DATABASE_URL}" 