[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
numReplicas = 1 