[build]
builder = "nixpacks"
buildCommand = "npm run build && npm run db:verify"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[deploy.env]
NODE_ENV = "production" 